provinsi = Province.create(provinsi: "DI Yogyakarta")

kabupaten = provinsi.regencies.create(kabupaten: "Bantul")
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Kasihan')
kecamatan.villages.create(kelurahan: 'Tirtonirmolo', kodepos: '55181')
kecamatan.villages.create(kelurahan: 'Ngestiharjo', kodepos: '55182')
kecamatan.villages.create(kelurahan: 'Tamantirto', kodepos: '55183')
kecamatan.villages.create(kelurahan: 'Bangunjiwo', kodepos: '55184')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Sewon')
kecamatan.villages.create(kelurahan: 'Pendowoharjo', kodepos: '55185')
kecamatan.villages.create(kelurahan: 'Timbulharjo', kodepos: '55186')
kecamatan.villages.create(kelurahan: 'Bangunharjo', kodepos: '55188')
kecamatan.villages.create(kelurahan: 'Panggungharjo', kodepos: '55188')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Banguntapan')
kecamatan.villages.create(kelurahan: 'Tamanan', kodepos: '55191')
kecamatan.villages.create(kelurahan: 'Jagalan', kodepos: '55192')
kecamatan.villages.create(kelurahan: 'Singosaren', kodepos: '55193')
kecamatan.villages.create(kelurahan: 'Wirokerten', kodepos: '55194')
kecamatan.villages.create(kelurahan: 'Jambidan', kodepos: '55195')
kecamatan.villages.create(kelurahan: 'Potorono', kodepos: '55196')
kecamatan.villages.create(kelurahan: 'Baturetno', kodepos: '55197')
kecamatan.villages.create(kelurahan: 'Banguntapan', kodepos: '55198')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Bantul')
kecamatan.villages.create(kelurahan: 'Bantul', kodepos: '55711')
kecamatan.villages.create(kelurahan: 'Ringin Harjo', kodepos: '55712')
kecamatan.villages.create(kelurahan: 'Palbapang', kodepos: '55713')
kecamatan.villages.create(kelurahan: 'Trirenggo', kodepos: '55714')
kecamatan.villages.create(kelurahan: 'Sabdodadi', kodepos: '55715')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Pajangan')
kecamatan.villages.create(kelurahan: 'Guwosari', kodepos: '55751')
kecamatan.villages.create(kelurahan: 'Sendangsari', kodepos: '55751')
kecamatan.villages.create(kelurahan: 'Triwidadi', kodepos: '55751')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Sedayu')
kecamatan.villages.create(kelurahan: 'Argodadi', kodepos: '55752')
kecamatan.villages.create(kelurahan: 'Argomulyo', kodepos: '55752')
kecamatan.villages.create(kelurahan: 'Argorejo', kodepos: '55752')
kecamatan.villages.create(kelurahan: 'Argosari', kodepos: '55752')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Pandak')
kecamatan.villages.create(kelurahan: 'Caturharjo', kodepos: '55761')
kecamatan.villages.create(kelurahan: 'Gilangharjo', kodepos: '55761')
kecamatan.villages.create(kelurahan: 'Triharjo', kodepos: '55761')
kecamatan.villages.create(kelurahan: 'Wijirejo', kodepos: '55761')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Srandakan')
kecamatan.villages.create(kelurahan: 'Poncosari', kodepos: '55762')
kecamatan.villages.create(kelurahan: 'Trimurti', kodepos: '55762')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Sanden')
kecamatan.villages.create(kelurahan: 'Gadingharjo', kodepos: '55763')
kecamatan.villages.create(kelurahan: 'Gadingsari', kodepos: '55763')
kecamatan.villages.create(kelurahan: 'Murtigading', kodepos: '55763')
kecamatan.villages.create(kelurahan: 'Srigading', kodepos: '55763')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Bambang Lipuro')
kecamatan.villages.create(kelurahan: 'Mulyodadi', kodepos: '55764')
kecamatan.villages.create(kelurahan: 'Sidomulyo', kodepos: '55764')
kecamatan.villages.create(kelurahan: 'Sumbermulyo', kodepos: '55764')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Pundong')
kecamatan.villages.create(kelurahan: 'Panjangrejo', kodepos: '55771')
kecamatan.villages.create(kelurahan: 'Seloharjo', kodepos: '55771')
kecamatan.villages.create(kelurahan: 'Srihardono', kodepos: '55771')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Kretek')
kecamatan.villages.create(kelurahan: 'Donotirto', kodepos: '55772')
kecamatan.villages.create(kelurahan: 'Parangtritis', kodepos: '55772')
kecamatan.villages.create(kelurahan: 'Tirtohargo', kodepos: '55772')
kecamatan.villages.create(kelurahan: 'Tirtomulyo', kodepos: '55772')
kecamatan.villages.create(kelurahan: 'Tirtosari', kodepos: '55772')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Jetis')
kecamatan.villages.create(kelurahan: 'Canden', kodepos: '55781')
kecamatan.villages.create(kelurahan: 'Patalan', kodepos: '55781')
kecamatan.villages.create(kelurahan: 'Sumber Agung', kodepos: '55781')
kecamatan.villages.create(kelurahan: 'Trimulyo', kodepos: '55781')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Imogiri')
kecamatan.villages.create(kelurahan: 'Girirejo', kodepos: '55782')
kecamatan.villages.create(kelurahan: 'Imogiri', kodepos: '55782')
kecamatan.villages.create(kelurahan: 'Karang Tengah', kodepos: '55782')
kecamatan.villages.create(kelurahan: 'Karangtalun', kodepos: '55782')
kecamatan.villages.create(kelurahan: 'Kebon Agung', kodepos: '55782')
kecamatan.villages.create(kelurahan: 'Selopamioro', kodepos: '55782')
kecamatan.villages.create(kelurahan: 'Sriharjo', kodepos: '55782')
kecamatan.villages.create(kelurahan: 'Wukirsari', kodepos: '55782')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Dlingo')
kecamatan.villages.create(kelurahan: 'Dlingo', kodepos: '55783')
kecamatan.villages.create(kelurahan: 'Jatimulyo', kodepos: '55783')
kecamatan.villages.create(kelurahan: 'Mangunan', kodepos: '55783')
kecamatan.villages.create(kelurahan: 'Muntuk', kodepos: '55783')
kecamatan.villages.create(kelurahan: 'Temuwuh', kodepos: '55783')
kecamatan.villages.create(kelurahan: 'Terong', kodepos: '55783')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Pleret')
kecamatan.villages.create(kelurahan: 'Bawuran', kodepos: '55791')
kecamatan.villages.create(kelurahan: 'Pleret', kodepos: '55791')
kecamatan.villages.create(kelurahan: 'Segoroyoso', kodepos: '55791')
kecamatan.villages.create(kelurahan: 'Wonokromo', kodepos: '55791')
kecamatan.villages.create(kelurahan: 'Wonolelo', kodepos: '55791')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Piyungan')
kecamatan.villages.create(kelurahan: 'Sitimulyo', kodepos: '55792')
kecamatan.villages.create(kelurahan: 'Srimartani', kodepos: '55792')
kecamatan.villages.create(kelurahan: 'Srimulyo', kodepos: '55792')

kabupaten = provinsi.regencies.create(kabupaten: "Gunung Kidul")
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Gedang Sari')
kecamatan.villages.create(kelurahan: 'Hargo Mulyo', kodepos: '55863')
kecamatan.villages.create(kelurahan: 'Mertelu', kodepos: '55863')
kecamatan.villages.create(kelurahan: 'Ngalang', kodepos: '55863')
kecamatan.villages.create(kelurahan: 'Sampang', kodepos: '55863')
kecamatan.villages.create(kelurahan: 'Serut', kodepos: '55863')
kecamatan.villages.create(kelurahan: 'Tegalrejo', kodepos: '55863')
kecamatan.villages.create(kelurahan: 'Watu Gajah', kodepos: '55863')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Girisubo')
kecamatan.villages.create(kelurahan: 'Balong', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Jepitu', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Jerukwudel', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Karangawen', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Nglindur', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Pucung', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Songbanyu', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Tileng', kodepos: '55883')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Karangmojo')
kecamatan.villages.create(kelurahan: 'Bejiharjo', kodepos: '55891')
kecamatan.villages.create(kelurahan: 'Bendungan', kodepos: '55891')
kecamatan.villages.create(kelurahan: 'Gedang Rejo', kodepos: '55891')
kecamatan.villages.create(kelurahan: 'Jati Ayu', kodepos: '55891')
kecamatan.villages.create(kelurahan: 'Karangmojo', kodepos: '55891')
kecamatan.villages.create(kelurahan: 'Kelor', kodepos: '55891')
kecamatan.villages.create(kelurahan: 'Ngawis', kodepos: '55891')
kecamatan.villages.create(kelurahan: 'Ngipak', kodepos: '55891')
kecamatan.villages.create(kelurahan: 'Wiladeg', kodepos: '55891')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Ngawen')
kecamatan.villages.create(kelurahan: 'Beji', kodepos: '55853')
kecamatan.villages.create(kelurahan: 'Jurang Jero', kodepos: '55853')
kecamatan.villages.create(kelurahan: 'Kampung', kodepos: '55853')
kecamatan.villages.create(kelurahan: 'Sambirejo', kodepos: '55853')
kecamatan.villages.create(kelurahan: 'Tancep', kodepos: '55853')
kecamatan.villages.create(kelurahan: 'Watu Sigar', kodepos: '55853')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Nglipar')
kecamatan.villages.create(kelurahan: 'Katongan', kodepos: '55852')
kecamatan.villages.create(kelurahan: 'Kedung Keris', kodepos: '55852')
kecamatan.villages.create(kelurahan: 'Kedungpoh', kodepos: '55852')
kecamatan.villages.create(kelurahan: 'Natah', kodepos: '55852')
kecamatan.villages.create(kelurahan: 'Nglipar', kodepos: '55852')
kecamatan.villages.create(kelurahan: 'Pengkol', kodepos: '55852')
kecamatan.villages.create(kelurahan: 'Pilang Rejo', kodepos: '55852')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Paliyan')
kecamatan.villages.create(kelurahan: 'Giring', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Grogol', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Karang Asem', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Karang Duwet', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Mulusan', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Pampang', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Sodo', kodepos: '55871')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Panggang')
kecamatan.villages.create(kelurahan: 'Giriharjo', kodepos: '55872')
kecamatan.villages.create(kelurahan: 'Girikarto', kodepos: '55872')
kecamatan.villages.create(kelurahan: 'Girimulyo', kodepos: '55872')
kecamatan.villages.create(kelurahan: 'Girisekar', kodepos: '55872')
kecamatan.villages.create(kelurahan: 'Girisuko', kodepos: '55872')
kecamatan.villages.create(kelurahan: 'Giriwungu', kodepos: '55872')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Patuk')
kecamatan.villages.create(kelurahan: 'Beji', kodepos: '55862')
kecamatan.villages.create(kelurahan: 'Bunder', kodepos: '55862')
kecamatan.villages.create(kelurahan: 'Nglanggeran', kodepos: '55862')
kecamatan.villages.create(kelurahan: 'Nglegi', kodepos: '55862')
kecamatan.villages.create(kelurahan: 'Ngoro Oro', kodepos: '55862')
kecamatan.villages.create(kelurahan: 'Patuk', kodepos: '55862')
kecamatan.villages.create(kelurahan: 'Pengkok', kodepos: '55862')
kecamatan.villages.create(kelurahan: 'Putat', kodepos: '55862')
kecamatan.villages.create(kelurahan: 'Salam', kodepos: '55862')
kecamatan.villages.create(kelurahan: 'Semoyo', kodepos: '55862')
kecamatan.villages.create(kelurahan: 'Terbah', kodepos: '55862')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Playen')
kecamatan.villages.create(kelurahan: 'Banaran', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Bandung', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Banyusoco', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Bleberan', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Dengok', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Gading', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Getas', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Logandeng', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Ngawu', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Ngleri', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Ngunut', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Playen', kodepos: '55861')
kecamatan.villages.create(kelurahan: 'Plembutan', kodepos: '55861')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Ponjong')
kecamatan.villages.create(kelurahan: 'Bedoyo', kodepos: '55892')
kecamatan.villages.create(kelurahan: 'Genjahan', kodepos: '55892')
kecamatan.villages.create(kelurahan: 'Gombang', kodepos: '55892')
kecamatan.villages.create(kelurahan: 'Karang Asem', kodepos: '55892')
kecamatan.villages.create(kelurahan: 'Kenteng', kodepos: '55892')
kecamatan.villages.create(kelurahan: 'Ponjong', kodepos: '55892')
kecamatan.villages.create(kelurahan: 'Sawahan', kodepos: '55892')
kecamatan.villages.create(kelurahan: 'Sidorejo', kodepos: '55892')
kecamatan.villages.create(kelurahan: 'Sumber Giri', kodepos: '55892')
kecamatan.villages.create(kelurahan: 'Tambakromo', kodepos: '55892')
kecamatan.villages.create(kelurahan: 'Umbul Rejo', kodepos: '55892')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Purwosari')
kecamatan.villages.create(kelurahan: 'Giriasih', kodepos: '55872')
kecamatan.villages.create(kelurahan: 'Giricahyo', kodepos: '55872')
kecamatan.villages.create(kelurahan: 'Girijati', kodepos: '55872')
kecamatan.villages.create(kelurahan: 'Giripurwo', kodepos: '55872')
kecamatan.villages.create(kelurahan: 'Giritirto', kodepos: '55872')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Rongkop')
kecamatan.villages.create(kelurahan: 'Bohol', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Botodayakan (Botodayaan)', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Karangwuni', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Melikan', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Petir', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Pringombo', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Pucanganom', kodepos: '55883')
kecamatan.villages.create(kelurahan: 'Semugih', kodepos: '55883')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Sapto Sari')
kecamatan.villages.create(kelurahan: 'Jetis', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Kanigoro', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Kepek', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Krambil Sawit', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Monggol', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Nglora', kodepos: '55871')
kecamatan.villages.create(kelurahan: 'Planjan', kodepos: '55871')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Semanu')
kecamatan.villages.create(kelurahan: 'Candirejo', kodepos: '55893')
kecamatan.villages.create(kelurahan: 'Dadapayu', kodepos: '55893')
kecamatan.villages.create(kelurahan: 'Ngeposari', kodepos: '55893')
kecamatan.villages.create(kelurahan: 'Pacarejo', kodepos: '55893')
kecamatan.villages.create(kelurahan: 'Semanu', kodepos: '55893')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Semin')
kecamatan.villages.create(kelurahan: 'Bendung', kodepos: '55854')
kecamatan.villages.create(kelurahan: 'Bulurejo', kodepos: '55854')
kecamatan.villages.create(kelurahan: 'Candi Rejo', kodepos: '55854')
kecamatan.villages.create(kelurahan: 'Kalitekuk', kodepos: '55854')
kecamatan.villages.create(kelurahan: 'Karang Sari', kodepos: '55854')
kecamatan.villages.create(kelurahan: 'Kemejing', kodepos: '55854')
kecamatan.villages.create(kelurahan: 'Pundung Sari', kodepos: '55854')
kecamatan.villages.create(kelurahan: 'Rejosari', kodepos: '55854')
kecamatan.villages.create(kelurahan: 'Semin', kodepos: '55854')
kecamatan.villages.create(kelurahan: 'Sumberrejo', kodepos: '55854')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Tanjungsari')
kecamatan.villages.create(kelurahan: 'Banjarejo', kodepos: '55881')
kecamatan.villages.create(kelurahan: 'Hargosari', kodepos: '55881')
kecamatan.villages.create(kelurahan: 'Kemadang', kodepos: '55881')
kecamatan.villages.create(kelurahan: 'Kemiri', kodepos: '55881')
kecamatan.villages.create(kelurahan: 'Ngestirejo', kodepos: '55881')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Tepus')
kecamatan.villages.create(kelurahan: 'Giripanggung', kodepos: '55881')
kecamatan.villages.create(kelurahan: 'Purwodadi', kodepos: '55881')
kecamatan.villages.create(kelurahan: 'Sidoharjo', kodepos: '55881')
kecamatan.villages.create(kelurahan: 'Sumber Wungu', kodepos: '55881')
kecamatan.villages.create(kelurahan: 'Tepus', kodepos: '55881')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Wonosari')
kecamatan.villages.create(kelurahan: 'Baleharjo', kodepos: '55811')
kecamatan.villages.create(kelurahan: 'Kepek', kodepos: '55813')
kecamatan.villages.create(kelurahan: 'Duwet', kodepos: '55851')
kecamatan.villages.create(kelurahan: 'Gari', kodepos: '55851')
kecamatan.villages.create(kelurahan: 'Karang Rejek', kodepos: '55851')
kecamatan.villages.create(kelurahan: 'Karang Tengah', kodepos: '55851')
kecamatan.villages.create(kelurahan: 'Mulo', kodepos: '55851')
kecamatan.villages.create(kelurahan: 'Piyaman', kodepos: '55851')
kecamatan.villages.create(kelurahan: 'Pulutan', kodepos: '55851')
kecamatan.villages.create(kelurahan: 'Selang', kodepos: '55851')
kecamatan.villages.create(kelurahan: 'Siraman', kodepos: '55851')
kecamatan.villages.create(kelurahan: 'Wareng', kodepos: '55851')
kecamatan.villages.create(kelurahan: 'Wonosari', kodepos: '55851')
kecamatan.villages.create(kelurahan: 'Wunung', kodepos: '55851')

kabupaten = provinsi.regencies.create(kabupaten: "Kulon Progo")
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Galur')
kecamatan.villages.create(kelurahan: 'Banaran', kodepos: '55661')
kecamatan.villages.create(kelurahan: 'Brosot', kodepos: '55661')
kecamatan.villages.create(kelurahan: 'Karang Sewu', kodepos: '55661')
kecamatan.villages.create(kelurahan: 'Kranggan', kodepos: '55661')
kecamatan.villages.create(kelurahan: 'Nomporejo', kodepos: '55661')
kecamatan.villages.create(kelurahan: 'Pandowan', kodepos: '55661')
kecamatan.villages.create(kelurahan: 'Tirta Rahayu', kodepos: '55661')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Girimulyo')
kecamatan.villages.create(kelurahan: 'Giripurwo', kodepos: '55674')
kecamatan.villages.create(kelurahan: 'Jatimulyo', kodepos: '55674')
kecamatan.villages.create(kelurahan: 'Pendoworejo', kodepos: '55674')
kecamatan.villages.create(kelurahan: 'Purwosari', kodepos: '55674')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Kalibawang')
kecamatan.villages.create(kelurahan: 'Banjararum', kodepos: '55672')
kecamatan.villages.create(kelurahan: 'Banjarasri', kodepos: '55672')
kecamatan.villages.create(kelurahan: 'Banjarharjo', kodepos: '55672')
kecamatan.villages.create(kelurahan: 'Banjaroyo', kodepos: '55672')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Kokap')
kecamatan.villages.create(kelurahan: 'Hargomulyo', kodepos: '55653')
kecamatan.villages.create(kelurahan: 'Hargorejo', kodepos: '55653')
kecamatan.villages.create(kelurahan: 'Hargotirto', kodepos: '55653')
kecamatan.villages.create(kelurahan: 'Hargowilis', kodepos: '55653')
kecamatan.villages.create(kelurahan: 'Kalirejo', kodepos: '55653')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Lendah')
kecamatan.villages.create(kelurahan: 'Bumirejo', kodepos: '55663')
kecamatan.villages.create(kelurahan: 'Gulurejo', kodepos: '55663')
kecamatan.villages.create(kelurahan: 'Jatirejo', kodepos: '55663')
kecamatan.villages.create(kelurahan: 'Ngentakrejo', kodepos: '55663')
kecamatan.villages.create(kelurahan: 'Sidorejo', kodepos: '55663')
kecamatan.villages.create(kelurahan: 'Wahyuharjo', kodepos: '55663')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Nanggulan')
kecamatan.villages.create(kelurahan: 'Banyuroto', kodepos: '55671')
kecamatan.villages.create(kelurahan: 'Donomulyo', kodepos: '55671')
kecamatan.villages.create(kelurahan: 'Jati Sarono', kodepos: '55671')
kecamatan.villages.create(kelurahan: 'Kembang', kodepos: '55671')
kecamatan.villages.create(kelurahan: 'Tanjungharjo', kodepos: '55671')
kecamatan.villages.create(kelurahan: 'Wijimulyo', kodepos: '55671')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Panjatan')
kecamatan.villages.create(kelurahan: 'Bojong', kodepos: '55655')
kecamatan.villages.create(kelurahan: 'Bugel', kodepos: '55655')
kecamatan.villages.create(kelurahan: 'Cerme', kodepos: '55655')
kecamatan.villages.create(kelurahan: 'Depok', kodepos: '55655')
kecamatan.villages.create(kelurahan: 'Garongan', kodepos: '55655')
kecamatan.villages.create(kelurahan: 'Gotakan', kodepos: '55655')
kecamatan.villages.create(kelurahan: 'Kanoman', kodepos: '55655')
kecamatan.villages.create(kelurahan: 'Krembangan', kodepos: '55655')
kecamatan.villages.create(kelurahan: 'Panjatan', kodepos: '55655')
kecamatan.villages.create(kelurahan: 'Pleret', kodepos: '55655')
kecamatan.villages.create(kelurahan: 'Tayuban', kodepos: '55655')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Pengasih')
kecamatan.villages.create(kelurahan: 'Karangsari', kodepos: '55652')
kecamatan.villages.create(kelurahan: 'Kedungsari', kodepos: '55652')
kecamatan.villages.create(kelurahan: 'Margosari', kodepos: '55652')
kecamatan.villages.create(kelurahan: 'Pengasih', kodepos: '55652')
kecamatan.villages.create(kelurahan: 'Sendangsari', kodepos: '55652')
kecamatan.villages.create(kelurahan: 'Sidomulyo', kodepos: '55652')
kecamatan.villages.create(kelurahan: 'Tawangsari', kodepos: '55652')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Samigaluh')
kecamatan.villages.create(kelurahan: 'Banjarsari', kodepos: '55673')
kecamatan.villages.create(kelurahan: 'Gerbosari', kodepos: '55673')
kecamatan.villages.create(kelurahan: 'Kebon Harjo', kodepos: '55673')
kecamatan.villages.create(kelurahan: 'Ngargosari', kodepos: '55673')
kecamatan.villages.create(kelurahan: 'Pagerharjo', kodepos: '55673')
kecamatan.villages.create(kelurahan: 'Purwoharjo', kodepos: '55673')
kecamatan.villages.create(kelurahan: 'Sidoharjo', kodepos: '55673')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Sentolo')
kecamatan.villages.create(kelurahan: 'Banguncipto', kodepos: '55664')
kecamatan.villages.create(kelurahan: 'Demangrejo', kodepos: '55664')
kecamatan.villages.create(kelurahan: 'Kaliagung', kodepos: '55664')
kecamatan.villages.create(kelurahan: 'Salamrejo', kodepos: '55664')
kecamatan.villages.create(kelurahan: 'Sentolo', kodepos: '55664')
kecamatan.villages.create(kelurahan: 'Srikayangan', kodepos: '55664')
kecamatan.villages.create(kelurahan: 'Sukoreno', kodepos: '55664')
kecamatan.villages.create(kelurahan: 'Tuksono', kodepos: '55664')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Temon')
kecamatan.villages.create(kelurahan: 'Demen', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Glagah', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Jangkaran', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Janten', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Kali Dengen', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Kaligintung', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Karang Wuluh', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Kebonrejo', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Kedundang', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Kulur', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Palihan', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Plumbon', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Sindutan', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Temon Kulon', kodepos: '55654')
kecamatan.villages.create(kelurahan: 'Temon Wetan', kodepos: '55654')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Wates')
kecamatan.villages.create(kelurahan: 'Bendungan', kodepos: '55651')
kecamatan.villages.create(kelurahan: 'Giri Peni', kodepos: '55651')
kecamatan.villages.create(kelurahan: 'Karang Wuni', kodepos: '55651')
kecamatan.villages.create(kelurahan: 'Kulwaru', kodepos: '55651')
kecamatan.villages.create(kelurahan: 'Ngestiharjo', kodepos: '55651')
kecamatan.villages.create(kelurahan: 'Sogan', kodepos: '55651')
kecamatan.villages.create(kelurahan: 'Triharjo', kodepos: '55651')
kecamatan.villages.create(kelurahan: 'Wates', kodepos: '55651')

kabupaten = provinsi.regencies.create(kabupaten: "Sleman")
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Berbah')
kecamatan.villages.create(kelurahan: 'Jogo Tirto', kodepos: '55573')
kecamatan.villages.create(kelurahan: 'Kali Tirto', kodepos: '55573')
kecamatan.villages.create(kelurahan: 'Sendang Tirto', kodepos: '55573')
kecamatan.villages.create(kelurahan: 'Tegal Tirto', kodepos: '55573')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Cangkringan')
kecamatan.villages.create(kelurahan: 'Argo Mulyo', kodepos: '55583')
kecamatan.villages.create(kelurahan: 'Glagah Harjo', kodepos: '55583')
kecamatan.villages.create(kelurahan: 'Kepuh Harjo', kodepos: '55583')
kecamatan.villages.create(kelurahan: 'Umbul Harjo', kodepos: '55583')
kecamatan.villages.create(kelurahan: 'Wukir Sari', kodepos: '55583')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Depok')
kecamatan.villages.create(kelurahan: 'Catur Tunggal', kodepos: '55281')
kecamatan.villages.create(kelurahan: 'Maguwoharjo', kodepos: '55282')
kecamatan.villages.create(kelurahan: 'Condong Catur', kodepos: '55283')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Gamping')
kecamatan.villages.create(kelurahan: 'Trihanggo', kodepos: '55291')
kecamatan.villages.create(kelurahan: 'Banyuraden', kodepos: '55293')
kecamatan.villages.create(kelurahan: 'Ambarketawang', kodepos: '55294')
kecamatan.villages.create(kelurahan: 'Balecatur', kodepos: '55295')
kecamatan.villages.create(kelurahan: 'Nogotirto', kodepos: '55592')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Godean')
kecamatan.villages.create(kelurahan: 'Sidoagung', kodepos: '55264')
kecamatan.villages.create(kelurahan: 'Sidoarum', kodepos: '55264')
kecamatan.villages.create(kelurahan: 'Sidokarto', kodepos: '55264')
kecamatan.villages.create(kelurahan: 'Sidoluhur', kodepos: '55264')
kecamatan.villages.create(kelurahan: 'Sidomoyo', kodepos: '55264')
kecamatan.villages.create(kelurahan: 'Sidomulyo', kodepos: '55264')
kecamatan.villages.create(kelurahan: 'Sidorejo', kodepos: '55264')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Kalasan')
kecamatan.villages.create(kelurahan: 'Purwo Martani', kodepos: '55571')
kecamatan.villages.create(kelurahan: 'Selo Martani', kodepos: '55571')
kecamatan.villages.create(kelurahan: 'Taman Martani', kodepos: '55571')
kecamatan.villages.create(kelurahan: 'Tirto Martani', kodepos: '55571')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Minggir')
kecamatan.villages.create(kelurahan: 'Sendang Arum', kodepos: '55562')
kecamatan.villages.create(kelurahan: 'Sendang Mulyo', kodepos: '55562')
kecamatan.villages.create(kelurahan: 'Sendang Rejo', kodepos: '55562')
kecamatan.villages.create(kelurahan: 'Sendangagung', kodepos: '55562')
kecamatan.villages.create(kelurahan: 'Sendangsari', kodepos: '55562')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Mlati')
kecamatan.villages.create(kelurahan: 'Sinduadi', kodepos: '55284')
kecamatan.villages.create(kelurahan: 'Sendangadi', kodepos: '55285')
kecamatan.villages.create(kelurahan: 'Tlogoadi', kodepos: '55286')
kecamatan.villages.create(kelurahan: 'Tirtoadi', kodepos: '55287')
kecamatan.villages.create(kelurahan: 'Sumberadi', kodepos: '55288')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Berbah')
kecamatan.villages.create(kelurahan: 'Sumber Agung', kodepos: '55563')
kecamatan.villages.create(kelurahan: 'Sumberarum', kodepos: '55563')
kecamatan.villages.create(kelurahan: 'Sumberrahayu', kodepos: '55563')
kecamatan.villages.create(kelurahan: 'Sumbersari', kodepos: '55563')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Ngaglik')
kecamatan.villages.create(kelurahan: 'Donoharjo', kodepos: '55581')
kecamatan.villages.create(kelurahan: 'Minomartani', kodepos: '55581')
kecamatan.villages.create(kelurahan: 'Sardonoharjo', kodepos: '55581')
kecamatan.villages.create(kelurahan: 'Sari Harjo', kodepos: '55581')
kecamatan.villages.create(kelurahan: 'Sinduharjo', kodepos: '55581')
kecamatan.villages.create(kelurahan: 'Suko Harjo', kodepos: '55581')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Ngemplak')
kecamatan.villages.create(kelurahan: 'Bimo Martani', kodepos: '55584')
kecamatan.villages.create(kelurahan: 'Sindumartani', kodepos: '55584')
kecamatan.villages.create(kelurahan: 'Umbulmartani', kodepos: '55584')
kecamatan.villages.create(kelurahan: 'Wedomartani', kodepos: '55584')
kecamatan.villages.create(kelurahan: 'Widodo Martani', kodepos: '55584')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Pakem')
kecamatan.villages.create(kelurahan: 'Candi Binangun', kodepos: '55582')
kecamatan.villages.create(kelurahan: 'Hargo Binangun', kodepos: '55582')
kecamatan.villages.create(kelurahan: 'Harjo Binangun', kodepos: '55582')
kecamatan.villages.create(kelurahan: 'Pakem Binangun', kodepos: '55582')
kecamatan.villages.create(kelurahan: 'Purwo Binangun', kodepos: '55582')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Prambanan')
kecamatan.villages.create(kelurahan: 'Boko Harjo', kodepos: '55572')
kecamatan.villages.create(kelurahan: 'Gayam Harjo', kodepos: '55572')
kecamatan.villages.create(kelurahan: 'Madu Rejo', kodepos: '55572')
kecamatan.villages.create(kelurahan: 'Sambi Rejo', kodepos: '55572')
kecamatan.villages.create(kelurahan: 'Sumber Harjo', kodepos: '55572')
kecamatan.villages.create(kelurahan: 'Wukir Harjo', kodepos: '55572')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Seyegan')
kecamatan.villages.create(kelurahan: 'Margoagung', kodepos: '55561')
kecamatan.villages.create(kelurahan: 'Margodadi', kodepos: '55561')
kecamatan.villages.create(kelurahan: 'Margokaton', kodepos: '55561')
kecamatan.villages.create(kelurahan: 'Margoluwih', kodepos: '55561')
kecamatan.villages.create(kelurahan: 'Margomulyo', kodepos: '55561')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Sleman')
kecamatan.villages.create(kelurahan: 'Tridadi', kodepos: '55511')
kecamatan.villages.create(kelurahan: 'Pandowo Harjo', kodepos: '55512')
kecamatan.villages.create(kelurahan: 'Tri Mulyo', kodepos: '55513')
kecamatan.villages.create(kelurahan: 'Triharjo', kodepos: '55514')
kecamatan.villages.create(kelurahan: 'Catur Harjo', kodepos: '55515')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Tempel')
kecamatan.villages.create(kelurahan: 'Banyu Rejo', kodepos: '55552')
kecamatan.villages.create(kelurahan: 'Lumbung Rejo', kodepos: '55552')
kecamatan.villages.create(kelurahan: 'Margo Rejo', kodepos: '55552')
kecamatan.villages.create(kelurahan: 'Merdiko Rejo', kodepos: '55552')
kecamatan.villages.create(kelurahan: 'Moro Rejo', kodepos: '55552')
kecamatan.villages.create(kelurahan: 'Pondok Rejo', kodepos: '55552')
kecamatan.villages.create(kelurahan: 'Sumber Rejo', kodepos: '55552')
kecamatan.villages.create(kelurahan: 'Tambak Rejo', kodepos: '55552')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Turi')
kecamatan.villages.create(kelurahan: 'Bangun Kerto', kodepos: '55551')
kecamatan.villages.create(kelurahan: 'Donokerto', kodepos: '55551')
kecamatan.villages.create(kelurahan: 'Giri Kerto', kodepos: '55551')
kecamatan.villages.create(kelurahan: 'Wono Kerto', kodepos: '55551')

kabupaten = provinsi.regencies.create(kabupaten: "Yogyakarta")
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Danurejan')
kecamatan.villages.create(kelurahan: 'Bausasran', kodepos: '55211')
kecamatan.villages.create(kelurahan: 'Tegal Panggung', kodepos: '55212')
kecamatan.villages.create(kelurahan: 'Suryatmajan', kodepos: '55213')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Gedong Tengen')
kecamatan.villages.create(kelurahan: 'Sosromenduran', kodepos: '55271')
kecamatan.villages.create(kelurahan: 'Pringgokusuman', kodepos: '55272')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Gondokusuman')
kecamatan.villages.create(kelurahan: 'Demangan', kodepos: '55221')
kecamatan.villages.create(kelurahan: 'Klitren', kodepos: '55222')
kecamatan.villages.create(kelurahan: 'Terban', kodepos: '55223')
kecamatan.villages.create(kelurahan: 'Kotabaru', kodepos: '55224')
kecamatan.villages.create(kelurahan: 'Baciro', kodepos: '55225')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Gondomanan')
kecamatan.villages.create(kelurahan: 'Prawirodirjan', kodepos: '55121')
kecamatan.villages.create(kelurahan: 'Ngupasan', kodepos: '55122')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Jetis')
kecamatan.villages.create(kelurahan: 'Bumijo', kodepos: '55231')
kecamatan.villages.create(kelurahan: 'Gowongan', kodepos: '55232')
kecamatan.villages.create(kelurahan: 'Cokrodiningratan', kodepos: '55233')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Kotagede')
kecamatan.villages.create(kelurahan: 'Rejowinangun', kodepos: '55171')
kecamatan.villages.create(kelurahan: 'Prenggan', kodepos: '55172')
kecamatan.villages.create(kelurahan: 'Purbayan', kodepos: '55173')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Kraton')
kecamatan.villages.create(kelurahan: 'Panembahan', kodepos: '55131')
kecamatan.villages.create(kelurahan: 'Kadipaten', kodepos: '55132')
kecamatan.villages.create(kelurahan: 'Patehan', kodepos: '55133')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Mantrijeron')
kecamatan.villages.create(kelurahan: 'Suryodiningratan', kodepos: '55141')
kecamatan.villages.create(kelurahan: 'Gedongkiwo', kodepos: '55142')
kecamatan.villages.create(kelurahan: 'Mantrijeron', kodepos: '55143')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Mergangsan')
kecamatan.villages.create(kelurahan: 'Wirogunan', kodepos: '55151')
kecamatan.villages.create(kelurahan: 'Keparakan', kodepos: '55152')
kecamatan.villages.create(kelurahan: 'Brontokusuman', kodepos: '55153')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Ngampilan')
kecamatan.villages.create(kelurahan: 'Ngampilan', kodepos: '55261')
kecamatan.villages.create(kelurahan: 'Notoprajan', kodepos: '55262')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Pakualaman')
kecamatan.villages.create(kelurahan: 'Gunung Ketur', kodepos: '55111')
kecamatan.villages.create(kelurahan: 'Purwo Kinanti', kodepos: '55112')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Tegalrejo')
kecamatan.villages.create(kelurahan: 'Karangwaru', kodepos: '55241')
kecamatan.villages.create(kelurahan: 'Kricak', kodepos: '55242')
kecamatan.villages.create(kelurahan: 'Bener', kodepos: '55243')
kecamatan.villages.create(kelurahan: 'Tegalrejo', kodepos: '55244')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Umbulharjo')
kecamatan.villages.create(kelurahan: 'Pandeyan', kodepos: '55161')
kecamatan.villages.create(kelurahan: 'Sorosutan', kodepos: '55162')
kecamatan.villages.create(kelurahan: 'Giwangan', kodepos: '55163')
kecamatan.villages.create(kelurahan: 'Warungboto', kodepos: '55164')
kecamatan.villages.create(kelurahan: 'Muja Muju', kodepos: '55165')
kecamatan.villages.create(kelurahan: 'Semaki', kodepos: '55166')
kecamatan.villages.create(kelurahan: 'Tahunan', kodepos: '55167')
kecamatan = kabupaten.subdistricts.create(kecamatan: 'Wirobrajan')
kecamatan.villages.create(kelurahan: 'Patangpuluhan', kodepos: '55251')
kecamatan.villages.create(kelurahan: 'Wirobrajan', kodepos: '55252')
kecamatan.villages.create(kelurahan: 'Pakuncen', kodepos: '55253')