DiseaseType.create!(name: "Asthma", main: true)
DiseaseType.create!(name: "Diare", main: true)
DiseaseType.create!(name: "Diabetes Melitus", main: true)
DiseaseType.create!(name: "Demam Berdarah", main: true)
DiseaseType.create!(name: "Gizi Buruk", main: true)
DiseaseType.create!(name: "Hipertensi", main: true)
DiseaseType.create!(name: "Jantung Koroner", main: true)
DiseaseType.create!(name: "Malaria", main: true)
DiseaseType.create!(name: "Stroke", main: true)
DiseaseType.create!(name: "Tuberkolosis", main: true)