image: "ruby:2.3.3"

services:
  - postgres:latest

variables:
  POSTGRES_DB: desasehat-api

cache:
  paths:
    - vendor/ruby

stages:
  - build
  - deploy

build:
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  stage: build
  script:
  - apt-get update && apt install -y -qq nodejs
  - gem install bundler  --no-ri --no-rdoc
  - gem install execjs
  # - RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
  # - bundle exec rake db:create db:schema:load
  # - bundle exec rake db:migrate
  # - bundle exec rake db:seed
  # - bundle exec rake assets:precompile
  except:
    - master

deploy to production:
  type: deploy
  stage: deploy
  environment: production
  script:
  - gem install dpl
  - dpl --provider=heroku --app=desasehat-api --api-key=849ca865-0343-494f-9652-87c731d06baa
  only:
  - master
