# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.4.3"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

variables:
  POSTGRES_DB: database_name

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - ruby -v                                   # Print out ruby version for debugging
  # Uncomment next line if your rails app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

# Optional - Delete if not using `rubocop`
# rubocop:
#   script:
#   - rubocop

rspec:
  script:
  - rspec spec

rails:
  variables:
    DATABASE_URL: "postgres://ljjaeqmcpuymib:192b76565409caec6c6e75ee0cb226af20e2ed06d0e253389f3bf2d885801c16@ec2-54-243-63-13.compute-1.amazonaws.com:5432/d99f5easv4gus3"
  script:
  - rails db:migrate
  - rails db:seed
  - rails test

# This deploy job uses a simple deploy flow to Heroku, other providers, e.g. AWS Elastic Beanstalk
# are supported too: https://github.com/travis-ci/dpl
deploy:
  type: deploy
  environment: production
  script:
  - gem install dpl
  - dpl --provider=heroku --app=desasehat-api --api-key=86627d609d55625527df962e77fa7d79479931dd6866e56014ebc80b2ade5f8f0d9a3ab7490bf29528e112029fd2fa91dc92d7e3bd199bfa15370b4667a87121
